import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ClientProvider from "@/ClientProvider";
import LayoutClient from "@/components/LayoutClient";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${inter.variable} font-sans antialiased`}>
          <ClientProvider>
       <LayoutClient> 
        <div className="pt-20">
        {children}
        </div>
        </LayoutClient> 
        <Toaster position="top-right" />
        </ClientProvider>
      </body>
    </html>
  );
}
